### ISSUE TITLE
pst use gofile instead

### ISSUE THREAD

**Issue by RaSan147** [X-Gorn/File-Sharing#4]
instead of heroku, try go file api. they stay as long as they can stay, built in video player and what not. you probably have time limit or something for files.

**Comment by xgorn** [comment]
@RaSan147 we're saving the files inside telegram server, which can be accessed from telegram without even downloading it (not inside heroku). and thanks for the idea, i'll try it.

**Comment by RaSan147** [comment]
Wait! You can direct link telegram files? 🤐

**Comment by xgorn** [comment]
@RaSan147 no. it's sharing link bot which means that it will share a link and you'll get the file after clicking on the link.

**Comment by RaSan147** [comment]
got itt, checked the source code. pretty neatly error handled
